//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LabNumber23.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class User
    {
        [Required]
        [RegularExpression(@"^[a-zA-Z]{2,30}$")]
        public string First_Name { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z]{2,30}$")]
        public string Last_Name { get; set; }

        [Required]
        [RegularExpression(@"^\d{3}-\d{3}-\d{4}$")]
        public string email { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z\d.]{5,20}@[a-zA-Z]{2,10}.[a-zA-Z]{1,3}$")]
        public string phone_number { get; set; }
    }

    



}
